const fs = require("node:fs");
const fsp = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");

const SYNTHETIC_HISTORY_HEADER = "# generated by codex-observatory from session logs";
const SYNTHETIC_HISTORY_MAX_FILE_BYTES_PREFIX = "# max-session-file-bytes=";
const DEFAULT_MAX_SESSION_FILE_BYTES = 256 * 1024 * 1024;

function parseMaxSessionFileBytes(rawValue) {
  const parsed = Number.parseInt(String(rawValue || ""), 10);
  if (!Number.isFinite(parsed) || parsed < 0) {
    return DEFAULT_MAX_SESSION_FILE_BYTES;
  }
  return parsed;
}

const MAX_SESSION_FILE_BYTES = parseMaxSessionFileBytes(process.env.CODEX_OBSERVATORY_MAX_SESSION_FILE_BYTES);

function parseSyntheticHistoryMetadata(rawLine) {
  if (!rawLine || !rawLine.startsWith(SYNTHETIC_HISTORY_MAX_FILE_BYTES_PREFIX)) {
    return null;
  }
  const parsed = Number.parseInt(rawLine.slice(SYNTHETIC_HISTORY_MAX_FILE_BYTES_PREFIX.length), 10);
  if (!Number.isFinite(parsed) || parsed < 0) {
    return null;
  }
  return parsed;
}

function expandHome(targetPath, homeDir = os.homedir()) {
  if (!targetPath) {
    return path.join(homeDir, ".codex");
  }
  if (targetPath === "~") {
    return homeDir;
  }
  if (targetPath.startsWith(`~${path.sep}`) || targetPath.startsWith("~/") || targetPath.startsWith("~\\")) {
    return path.join(homeDir, targetPath.slice(2));
  }
  return targetPath;
}

function readCliValue(argv, flagName) {
  for (let index = 0; index < argv.length; index += 1) {
    const current = argv[index];
    if (current === flagName) {
      return argv[index + 1] || null;
    }
    if (current.startsWith(`${flagName}=`)) {
      return current.slice(flagName.length + 1);
    }
  }
  return null;
}

function hasSupportedCodexData(codexHome) {
  return (
    fs.existsSync(path.join(codexHome, "history.jsonl")) ||
    fs.existsSync(path.join(codexHome, "session_index.jsonl")) ||
    fs.existsSync(path.join(codexHome, "sessions"))
  );
}

function resolveCodexHome(argv = [], env = process.env, homeDir = os.homedir()) {
  const requested = readCliValue(argv, "--codex-home") || env.CODEX_HOME || path.join(homeDir, ".codex");
  const candidate = path.resolve(expandHome(requested, homeDir));
  if (hasSupportedCodexData(candidate)) {
    return candidate;
  }
  const nested = path.join(candidate, ".codex");
  if (hasSupportedCodexData(nested)) {
    return nested;
  }
  return candidate;
}

function* readJsonlLines(filePath) {
  if (!fs.existsSync(filePath)) {
    return;
  }

  let fileDescriptor;
  try {
    fileDescriptor = fs.openSync(filePath, "r");
  } catch {
    return;
  }

  const chunkSize = 1024 * 1024;
  const buffer = Buffer.allocUnsafe(chunkSize);
  let remainder = "";

  try {
    while (true) {
      const bytesRead = fs.readSync(fileDescriptor, buffer, 0, chunkSize, null);
      if (bytesRead <= 0) {
        break;
      }

      const chunkText = remainder + buffer.toString("utf8", 0, bytesRead);
      const chunkLines = chunkText.split(/\r?\n/);
      remainder = chunkLines.pop() || "";

      for (const line of chunkLines) {
        if (line.trim()) {
          yield line;
        }
      }
    }

    if (remainder.trim()) {
      yield remainder;
    }
  } catch {
    return;
  } finally {
    try {
      fs.closeSync(fileDescriptor);
    } catch {
      // close is best-effort
    }
  }
}

function toUnixSeconds(rawTimestamp, fallbackMs) {
  const parsedMs = rawTimestamp ? Date.parse(String(rawTimestamp)) : Number.NaN;
  const effectiveMs = Number.isFinite(parsedMs) ? parsedMs : fallbackMs;
  return Math.floor(effectiveMs / 1000);
}

function responseItemUserText(payload) {
  return (payload.content || [])
    .map((part) => (part && typeof part.text === "string" ? part.text.trim() : ""))
    .filter(Boolean)
    .join("\n")
    .trim();
}

function isEnvironmentContextPrompt(text) {
  return text.trimStart().startsWith("<environment_context>");
}

function buildPromptRowsFromSessionFile(sessionFile) {
  let fallbackMs = Date.now();
  try {
    const stats = fs.statSync(sessionFile);
    if (MAX_SESSION_FILE_BYTES > 0 && stats.size > MAX_SESSION_FILE_BYTES) {
      return [];
    }
    fallbackMs = stats.mtimeMs;
  } catch {
    // Keep the default fallback timestamp when stat fails.
  }
  let sessionId = path.basename(sessionFile, path.extname(sessionFile));
  const explicitRows = [];
  const fallbackRows = [];

  for (const line of readJsonlLines(sessionFile)) {
    let item;
    try {
      item = JSON.parse(line);
    } catch {
      continue;
    }

    const payload = item.payload || {};
    if (item.type === "session_meta") {
      sessionId = String(payload.id || sessionId);
      continue;
    }

    const row = {
      session_id: sessionId,
      ts: toUnixSeconds(item.timestamp, fallbackMs)
    };

    if (item.type === "event_msg" && payload.type === "user_message") {
      const message = String(payload.message || "").trim();
      if (message) {
        explicitRows.push(row);
      }
      continue;
    }

    if (item.type === "response_item" && payload.type === "message" && payload.role === "user") {
      const promptText = responseItemUserText(payload);
      if (promptText && !isEnvironmentContextPrompt(promptText)) {
        fallbackRows.push(row);
      }
    }
  }

  return explicitRows.length ? explicitRows : fallbackRows;
}

function collectJsonlFiles(rootDir) {
  const files = [];
  for (const entry of fs.readdirSync(rootDir, { withFileTypes: true })) {
    const fullPath = path.join(rootDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectJsonlFiles(fullPath));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith(".jsonl")) {
      files.push(fullPath);
    }
  }
  return files;
}

function collectSessionJsonlFiles(codexHome) {
  const sessionsRoot = path.join(codexHome, "sessions");
  if (!fs.existsSync(sessionsRoot)) {
    return [];
  }
  const files = collectJsonlFiles(sessionsRoot).sort();
  if (MAX_SESSION_FILE_BYTES <= 0) {
    return files;
  }
  return files.filter((filePath) => {
    try {
      return fs.statSync(filePath).size <= MAX_SESSION_FILE_BYTES;
    } catch {
      return false;
    }
  });
}

function newestMtimeMs(filePaths) {
  let newest = 0;
  for (const filePath of filePaths) {
    try {
      const current = fs.statSync(filePath).mtimeMs;
      if (current > newest) {
        newest = current;
      }
    } catch {
      // Ignore stat errors for individual files.
    }
  }
  return newest;
}

function collectPromptRowsFromSessions(codexHome) {
  return collectSessionJsonlFiles(codexHome)
    .flatMap((sessionFile) => buildPromptRowsFromSessionFile(sessionFile))
    .sort((left, right) => left.ts - right.ts || left.session_id.localeCompare(right.session_id));
}

function readSyntheticHistoryMetadata(historyPath) {
  if (!fs.existsSync(historyPath)) {
    return { synthetic: false, maxSessionFileBytes: null };
  }
  const [firstLine = "", secondLine = ""] = fs.readFileSync(historyPath, "utf8").split(/\r?\n/, 2);
  return {
    synthetic: firstLine.startsWith(SYNTHETIC_HISTORY_HEADER),
    maxSessionFileBytes: parseSyntheticHistoryMetadata(secondLine)
  };
}

async function syncPromptHistory(codexHome) {
  const historyPath = path.join(codexHome, "history.jsonl");
  const historyExists = fs.existsSync(historyPath);
  const historyMetadata = historyExists ? readSyntheticHistoryMetadata(historyPath) : { synthetic: false, maxSessionFileBytes: null };
  const syntheticHistory = historyMetadata.synthetic;
  if (historyExists && !syntheticHistory) {
    return { updated: false, created: false, historyPath };
  }

  const sessionFiles = collectSessionJsonlFiles(codexHome);
  if (!sessionFiles.length) {
    return { updated: false, created: false, historyPath };
  }

  if (historyExists && syntheticHistory && historyMetadata.maxSessionFileBytes === MAX_SESSION_FILE_BYTES) {
    let historyMtimeMs = 0;
    try {
      historyMtimeMs = fs.statSync(historyPath).mtimeMs;
    } catch {
      historyMtimeMs = 0;
    }
    if (historyMtimeMs >= newestMtimeMs(sessionFiles)) {
      return { updated: false, created: false, historyPath };
    }
  }

  const rows = sessionFiles
    .flatMap((sessionFile) => buildPromptRowsFromSessionFile(sessionFile))
    .sort((left, right) => left.ts - right.ts || left.session_id.localeCompare(right.session_id));
  if (!rows.length) {
    return { updated: false, created: false, historyPath };
  }

  await fsp.mkdir(codexHome, { recursive: true });
  const body = `${SYNTHETIC_HISTORY_HEADER}\n${SYNTHETIC_HISTORY_MAX_FILE_BYTES_PREFIX}${MAX_SESSION_FILE_BYTES}\n${rows.map((row) => JSON.stringify(row)).join("\n")}\n`;
  await fsp.writeFile(historyPath, body, "utf8");
  return { updated: true, created: !historyExists, historyPath, rowCount: rows.length };
}

function escapePowerShellSingle(value) {
  return value.replace(/'/g, "''");
}

function shellQuote(value) {
  return `'${value.replace(/'/g, `'\"'\"'`)}'`;
}

async function rewriteNpmToolScripts(codexHome, { nodePath, entryScriptPath }) {
  const toolsDir = path.join(codexHome, "tools");
  const ps1Path = path.join(toolsDir, "codex-stats.ps1");
  const shPath = path.join(toolsDir, "codex-stats.sh");
  await fsp.mkdir(toolsDir, { recursive: true });

  const resolvedNode = path.resolve(nodePath);
  const resolvedEntry = path.resolve(entryScriptPath);

  const ps1Content = [
    "param(",
    "    [Parameter(ValueFromRemainingArguments = $true)]",
    "    [string[]]$CliArgs",
    ")",
    "",
    `$node = '${escapePowerShellSingle(resolvedNode)}'`,
    `$script = '${escapePowerShellSingle(resolvedEntry)}'`,
    "& $node $script @CliArgs",
    "exit $LASTEXITCODE",
    ""
  ].join("\n");

  const shContent = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    `exec ${shellQuote(resolvedNode)} ${shellQuote(resolvedEntry)} "$@"`,
    ""
  ].join("\n");

  await fsp.writeFile(ps1Path, ps1Content, "utf8");
  await fsp.writeFile(shPath, shContent, "utf8");
  try {
    await fsp.chmod(shPath, 0o755);
  } catch {
    // chmod is best-effort on Windows.
  }

  return { ps1Path, shPath };
}

module.exports = {
  SYNTHETIC_HISTORY_HEADER,
  buildPromptRowsFromSessionFile,
  collectPromptRowsFromSessions,
  hasSupportedCodexData,
  resolveCodexHome,
  rewriteNpmToolScripts,
  syncPromptHistory
};
